export const ActionTypes = {
    CREATE_DRIVER : "CREATE_DRIVER",
    FETCH_DRIVERS : "FETCH_DRIVERS",
    FETCH_DRIVER : "FETCH_DRIVER",
    UPDATE_DRIVER : "UPDATE_DRIVER",
    DELETE_DRIVER : "DELETE_DRIVER"
}