export const ActionTypes = {
    CREATE_DRIVER : "CREATE_DRIVER",
    FETCH_DRIVERS : "FETCH_DRIVERS",
    FETCH_DRIVER : "FETCH_DRIVER",
    UPDATE_DRIVER : "UPDATE_DRIVER",
    DELETE_DRIVER : "DELETE_DRIVER",
    CREATE_CAB : "CREATE_CAB",
    FETCH_CABS : "FETCH_CABS",
    FETCH_CAB : "FETCH_CAB",
    UPDATE_CAB : "UPDATE_CAB",
    DELETE_CAB : "DELETE_CAB",
}